"use client";

import { useState } from "react";
import { Shield, Key, Smartphone } from "lucide-react";

export default function SecurityPage() {
  const [loading, setLoading] = useState(false);
  const [saved, setSaved] = useState(false);

  const handlePasswordChange = (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    }, 1000);
  };

  return (
    <div className="space-y-6 max-w-4xl">
      <div>
        <h1 className="text-2xl font-bold text-gray-900">Security Settings</h1>
        <p className="mt-1 text-sm text-gray-500">
          Manage your password and two-factor authentication.
        </p>
      </div>

      {/* Change Password */}
      <form onSubmit={handlePasswordChange} className="bg-white shadow-sm ring-1 ring-gray-200 rounded-xl overflow-hidden">
        <div className="border-b border-gray-200 bg-gray-50 px-6 py-4 flex items-center gap-2">
          <Key className="h-5 w-5 text-gray-400" />
          <h2 className="text-base font-semibold text-gray-900">Change Password</h2>
        </div>
        <div className="p-6 space-y-4">
          <div>
            <label htmlFor="current" className="block text-sm font-medium text-gray-700">Current Password</label>
            <input type="password" id="current" className="mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-orange-600 sm:text-sm sm:leading-6 px-3 max-w-md" />
          </div>
          <div>
            <label htmlFor="new" className="block text-sm font-medium text-gray-700">New Password</label>
            <input type="password" id="new" className="mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-orange-600 sm:text-sm sm:leading-6 px-3 max-w-md" />
          </div>
          <div>
            <label htmlFor="confirm" className="block text-sm font-medium text-gray-700">Confirm New Password</label>
            <input type="password" id="confirm" className="mt-2 block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:ring-2 focus:ring-inset focus:ring-orange-600 sm:text-sm sm:leading-6 px-3 max-w-md" />
          </div>
        </div>
        <div className="bg-gray-50 px-6 py-4 flex items-center justify-end gap-4 border-t border-gray-200">
          {saved && <span className="text-sm text-green-600">Password updated!</span>}
          <button type="submit" disabled={loading} className="rounded-md bg-slate-900 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-slate-800 disabled:opacity-50">
            {loading ? "Updating..." : "Update Password"}
          </button>
        </div>
      </form>

      {/* Two-Factor Authentication */}
      <div className="bg-white shadow-sm ring-1 ring-gray-200 rounded-xl overflow-hidden">
        <div className="border-b border-gray-200 bg-gray-50 px-6 py-4 flex items-center gap-2">
          <Smartphone className="h-5 w-5 text-gray-400" />
          <h2 className="text-base font-semibold text-gray-900">Two-Factor Authentication (2FA)</h2>
        </div>
        <div className="p-6">
          <div className="flex items-start gap-4">
            <div className="bg-orange-100 p-3 rounded-full flex-shrink-0">
              <Shield className="h-6 w-6 text-orange-600" />
            </div>
            <div>
              <h3 className="text-lg font-medium text-gray-900">Protect your account with 2FA</h3>
              <p className="mt-1 text-sm text-gray-500">
                Two-factor authentication adds an extra layer of security to your account. Once enabled, you'll be required to enter a code generated by an authenticator app on your phone during login.
              </p>
              <div className="mt-4">
                <button type="button" className="rounded-md bg-white px-4 py-2 text-sm font-semibold text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 hover:bg-gray-50">
                  Enable 2FA
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
